import { prisma } from "../../databases/client";
import { generateSecret } from "../../utils/generateSecret.util";
import type { Prisma } from "@prisma/client";

/** Input for creating a single ClientApp (secret is generated by the service). */
type ClientAppCreateInput = Omit<Prisma.ClientAppCreateInput, "secret">;

/** Input for createMany (secret is generated per item). */
type ClientAppCreateManyItem = { name: string, description: string, isActive: boolean, createdAt: Date };

// Types
type ServiceData = {
    id: string;
    name: string;
    baseUrl: string;
    createdAt: Date;
};

type RouteData = {
    id: string;
    exposedPath: string;
    actualPath: string;
    method: string;
    service?: ServiceData;
};

type PermissionData = {
    id: string;
    route?: RouteData;
};

// Helper Functions
function mapPermissionsForGateway(permissions: PermissionData[]) {
    return (permissions || []).map((perm) => ({
        id: perm.id,
        path: perm.route?.exposedPath || "",
        internalPath: perm.route?.actualPath || "",
        method: perm.route?.method,
        route: perm.route,
        service: perm.route?.service,
    }));
}

// Service
export class ClientAppService {
    private static instance: ClientAppService;

    static getInstance(): ClientAppService {
        if (!ClientAppService.instance) {
            ClientAppService.instance = new ClientAppService();
        }
        return ClientAppService.instance;
    }

    // Read Operations
    async getClientAppById(id: string): Promise<Prisma.ClientAppGetPayload<true> | null> {
        return prisma.clientApp.findUnique({
            where: { id },
        });
    }

    async getClientAppByIdWithRoutePermissions(id: string) {
        const app = await prisma.clientApp.findUnique({
            where: { id },
            include: {
                permissions: {
                    include: {
                        route: {
                            include: {
                                service: true,
                            },
                        },
                    },
                },
            },
        });

        if (!app) return null;

        return {
            ...app,
            permissions: mapPermissionsForGateway(app.permissions),
        };
    }

    async getAllClientApps(): Promise<Prisma.ClientAppGetPayload<true>[]> {
        return prisma.clientApp.findMany();
    }

    // Create Operations
    async createClientApp(data: ClientAppCreateInput): Promise<Prisma.ClientAppGetPayload<true>> {
        return prisma.clientApp.create({
            data: { ...data, secret: generateSecret() },
        });
    }

    async createBulkClientApps(apps: ClientAppCreateManyItem[]): Promise<{ count: number }> {
        return prisma.clientApp.createMany({
            data: apps.map((app) => ({ ...app, secret: generateSecret() })),
        });
    }

    // Update Operations
    async updateClientApp(data: Partial<Omit<Prisma.ClientAppUpdateInput, "id">> & { id: string }): Promise<Prisma.ClientAppGetPayload<true>> {
        const { id, ...updateData } = data;
        return prisma.clientApp.update({
            where: { id },
            data: updateData,
        });
    }

    async updateBulkClientApps(apps: (Partial<Omit<Prisma.ClientAppUpdateInput, "id">> & { id: string })[]): Promise<{ count: number }> {
        const promises = apps.map((app) => this.updateClientApp(app));
        await Promise.all(promises);
        return { count: apps.length };
    }

    // Delete Operations
    async deleteClientApp(id: string): Promise<Prisma.ClientAppGetPayload<true>> {
        return prisma.clientApp.delete({
            where: { id },
        });
    }

    async deleteBulkClientApps(apps: { id: string }[]): Promise<{ count: number }> {
        const promises = apps.map((app) => this.deleteClientApp(app.id));
        await Promise.all(promises);
        return { count: apps.length };
    }

    // Key Rotation Operations
    async rotateSecret(id: string): Promise<Prisma.ClientAppGetPayload<true>> {
        const newSecret = generateSecret();
        return prisma.clientApp.update({
            where: { id },
            data: { secret: newSecret },
        });
    }
}