info:
  name: Update Applications In Bulk
  type: http
  seq: 6

http:
  method: PUT
  url: "{{sitePlatformBaseUrl}}/api/admin/applications/bulk"
  headers:
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      [
          {
                  "id": "034896ea-7e69-440c-8611-dda14e1999a0",
                  "name": "App 3",
                  "description": "Third app",
                  "isActive": true
              },
              {
                  "id": "8e018b45-a5d1-4caf-928d-5d994d6340ec",
                  "name": "App 4",
                  "description": "Fourth app",
                  "isActive": true
              }
        ]
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Update Applications In Bulk
    request:
      url: "{{sitePlatformBaseUrl}}/api/admin/applications/bulk"
      method: PUT
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          [
              {
                      "id": "034896ea-7e69-440c-8611-dda14e1999a0",
                      "name": "App 3",
                      "description": "Third app",
                      "isActive": true
                  },
                  {
                      "id": "8e018b45-a5d1-4caf-928d-5d994d6340ec",
                      "name": "App 4",
                      "description": "Fourth app",
                      "isActive": true
                  }
            ]
    response:
      statusText: "200"
      headers:
        - name: Vary
          value: Origin
        - name: Access-Control-Allow-Credentials
          value: "true"
        - name: Access-Control-Expose-Headers
          value: X-Total-Count,X-Page-Count
        - name: Content-Security-Policy
          value: "default-src 'self';style-src 'self' 'unsafe-inline';script-src 'self';img-src 'self' data: https:;connect-src 'self';font-src 'self';object-src 'none';media-src 'self';frame-src 'none';base-uri 'self';form-action 'self';frame-ancestors 'self';script-src-attr 'none';upgrade-insecure-requests"
        - name: Cross-Origin-Opener-Policy
          value: same-origin
        - name: Cross-Origin-Resource-Policy
          value: same-origin
        - name: Origin-Agent-Cluster
          value: ?1
        - name: Referrer-Policy
          value: no-referrer
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains; preload
        - name: X-Content-Type-Options
          value: nosniff
        - name: X-DNS-Prefetch-Control
          value: off
        - name: X-Download-Options
          value: noopen
        - name: X-Frame-Options
          value: DENY
        - name: X-XSS-Protection
          value: 1; mode=block
        - name: Content-Type
          value: application/json; charset=utf-8
        - name: Content-Length
          value: "35"
        - name: ETag
          value: W/"23-5fQqYsQcgozxCAW717bVgsb59Wk"
        - name: Date
          value: Fri, 27 Feb 2026 11:04:44 GMT
        - name: Connection
          value: keep-alive
        - name: Keep-Alive
          value: timeout=5
      body:
        type: json
        data: |-
          {
              "success": true,
              "data": {
                  "count": 2
              }
          }
